- name: Playbook to configure ansible controller post installation
  hosts: instance-9
  vars:
    workflow_job_templates_secure_logging: false
    controller_validate_certs: false
    controller_hostname: instance-9
    controller_username: "{{ lookup('env', 'admin_name') }}"
    controller_password: "{{ lookup('env', 'admin_password') }}"
  collections:
    - awx.awx
    - redhat_cop.controller_configuration

  pre_tasks:
    - name: Include vars from controller_configs directory
      include_vars:
        dir: ./configs_export_model
        extensions: ["yml"]

  roles:
    - {role: organizations, when: controller_organizations is defined, tags: organizations}
    - {role: users, when: controller_user_accounts is defined, tags: users}
    - {role: teams, when: controller_teams is defined, tags: teams}
    - {role: credential_types, when: controller_credential_types is defined, tags: credential_types}
    - {role: credentials, when: controller_credentials is defined, tags: credentials}
    - {role: inventories, when: controller_inventories is defined, tags: inventories}
    - {role: inventory_sources, when: controller_inventory_sources is defined, tags: inventory_sources}
    - {role: projects, when: controller_projects is defined, tags: projects}
    - {role: project_update, when: controller_projects is defined, tags: projects}
    - {role: job_templates, when: controller_templates is defined, tags: job_templates}
    - {role: workflow_job_templates, when: controller_workflows is defined, tags: workflow_job_templates}
    - {role: notification_templates, when: controller_notifications is defined, tags: notification_templates}







