- name: Remove all objects from Ansible Tower
  hosts: instance-9
  gather_facts: no
  tasks:
    - name: Delete all objects from Ansible Tower
      shell: echo YES | tower-cli empty --all -v -u "{{ lookup('env', 'admin_name') }}" -p "{{ lookup('env', 'admin_password') }}" -h "http://localhost" --insecure