name: My Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Remove objects from Ansible Automation Platform
        run: |
          ansible-playbook remove.yml
      - name: Build Ansible Automation Platform conf state
        run: |
          ansible-playbook main.yml
